In [16]:
import pandas as pd
import matplotlib.pyplot as plt


dt = pd.read_csv("https://github.com/febse/econ2026/raw/refs/heads/main/data/ggb.csv")

dt.head()

  sex drug  ha
0   F    N   1
1   M    N   1
2   M    N   1
3   M    N   1
4   M    N   1

drug
N    20.312500
Y    15.873016
Name: ha, dtype: float64

In [ ]:
from statsmodels.formula.api import ols

model1 = ols("", data=dt).fit()
model1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     ha   R-squared:                       0.101
Model:                            OLS   Adj. R-squared:                  0.094
Method:                 Least Squares   F-statistic:                     14.05
Date:                Tue, 07 Apr 2026   Prob (F-statistic):           0.000271
Time:                        09:30:55   Log-Likelihood:                -52.251
No. Observations:                 127   AIC:                             108.5
Df Residuals:                     125   BIC:                             114.2
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0615      0.046      1.348      0.180      -0.029       0.152
sex[T.M]       0.2449      0.065      3.749      0.000       0.116       0.374
==============================================================================
Omnibus:                       28.746   Durbin-Watson:                   0.055
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               40.285
Skew:                           1.358   Prob(JB):                     1.79e-09
Kurtosis:                       3.490   Cond. No.                         2.59
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:
# Read the data
crime = pd.read_csv("https://raw.githubusercontent.com/febse/data/main/econ/crime.csv", delimiter="\t")

# Drop the 'I' column
crime = crime.drop(columns=['I'])
crime.head()

     County    C    HS     U
0   ALACHUA  104  82.7  73.2
1     BAKER   20  64.1  21.5
2       BAY   64  74.7  85.0
3  BRADFORD   50  65.0  23.2
4   BREVARD   64  82.3  91.9